# Outputting
# permalink: /:categories/:year/:month/:day/:title.html

# Conversion
# markdown:         kramdown
# highlighter:      rouge
# excerpt_separator: <!--more-->

# Config for your profile.
title:            Welcome to my blog            # Site title
name:             Sravan            # Your name
avatar:           /theme/img/sravan_github_profile_img.png   # Path to an avatar image


# The theme uses the baseurl throughout, which is useful for running the entire
# site under a subdir, like for this GitHub Pages deployment as a project site.
# baseurl: "/gh-pages"

# Add a directory to hold misc pages, just to keep the root directory clean.
include: ["_pages", "_portfolio"]

# Wire in the SASS files in the theme directory.
sass:
  sass_dir: theme/_sass
  style: compressed

# Turn the projects into a collection.
collections:
  projects:
    output: true
    title: Projects
    permalink: /:collection/:name.html
  portfolio:
    output: true
    title: portfolio
    permalink: /:collection/:name.html

defaults:
  -
    scope:
      path: ""
    values:
      show_profile: true
  -
    scope:
      path: "_posts"
    values:
      show_profile: true
      layout: defaults/post
  -
    scope:
      path: "_portfolio"
    values:
      show_profile: false
      layout: defaults/portfolio
  -
    scope:
      path: "_projects"
    values:
      show_profile: false
      layout: defaults/project
  -
    scope:
      path: "list"
    values:
      show_profile: false
      layout: defaults/list


